---
# To target ConnectX-6 Dx, use nicType: "101d"
# To target ConnectX-7, use nicType: "1021"
# To target bluefield-2, use nicType: "a2d6"
# To target bluefield-3, use nicType: "a2dc"
# See: https://github.com/Mellanox/nic-configuration-operator
apiVersion: configuration.net.nvidia.com/v1alpha1
kind: NicConfigurationTemplate
metadata:
  name: rocev2-gpudirect-config
  namespace: nvidia-network-operator
spec:
  nodeSelector:
    feature.node.kubernetes.io/pci-15b3.present: "true"
  nicSelector:
    nicType: "101d"
  resetToDefault: false
  template:
    numVfs: 0
    linkType: Ethernet
    pciPerformanceOptimized:
      enabled: true
      maxAccOutRead: 44
      maxReadRequest: 4096
    roceOptimized:
      enabled: true
      qos:
        trust: "dscp"
        pfc: "0,0,0,1,0,0,0,0"
    gpuDirectOptimized:
      enabled: true
      env: "Baremetal"
